name: Lint and build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        run: npm i

      - name: Run TypeScript Compiler
        run: npm run tsc

      - name: Run ESLint
        run: npm run lint
    permissions:
      contents: read
      pull-requests: read
      checks: write

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        run: npm i

      - name: Build
        run: npm run build
    permissions:
      contents: read
      pull-requests: read
      checks: write

  build-storybook:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        run: npm i

      - name: Build
        run: npm run build-storybook
    permissions:
      contents: read
      pull-requests: read
      checks: write
