# Copyright (c) 2023 Anass Bouassaba.
#
# Use of this software is governed by the MIT License
# included in the file LICENSE in the root of this repository.

name: Lint and Build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages
        run: bun i

      - name: Build
        run: bun run build
    permissions:
      contents: read
      pull-requests: read
      checks: write

  storybook-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages
        run: bun i

      - name: Build
        run: bun run build

      - name: Build Storybook
        run: bun run storybook:build
    permissions:
      contents: read
      pull-requests: read
      checks: write

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
      - storybook-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun i

      - name: Build
        run: bun run build

      - name: Run TypeScript Compiler
        run: bun run tsc

      - name: Run ESLint
        run: bun run lint
    permissions:
      contents: read
      pull-requests: read
      checks: write
